# Generated by Django 5.0.6 on 2026-04-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_no_show_count_user_total_appointments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('receptionist', 'Receptionist'), ('admin', 'Admin'), ('lab_staff', 'Laboratory Staff'), ('imaging_staff', 'Imaging Staff')], default='patient', max_length=20),
        ),
    ]
